### ISSUE TITLE
Mod is incompatible with latest version of Create

### ISSUE THREAD

**Issue by CaptainSqrBeard** [jmcmahon1999/createeditions#1]
## Used mods
- createeditions-1.0.1+1.20.1_fabric.jar
- create-fabric-0.5.1-f-build.1417+mc1.20.1.jar

## Log
```
[11:57:57] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[11:57:57] [main/WARN]: Mod resolution failed
[11:57:57] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE createeditions 1.0.1+1.20.1_fabric {depends create @ [0.5.1-d-build.1161+mc1.20.1]}, ROOT_FORCELOAD_SINGLE createeditions 1.0.1+1.20.1_fabric]
[11:57:57] [main/INFO]: Reason: [HARD_DEP createeditions 1.0.1+1.20.1_fabric {depends create @ [0.5.1-d-build.1161+mc1.20.1]}]
[11:57:57] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.1-f-build.1417+mc1.20.1] -> add:create 0.5.1-d-build.1161+mc1.20.1 ([[0.5.1-d-build.1161+mc1.20.1,0.5.1-d-build.1161+mc1.20.1]])]
[11:57:57] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-f-build.1417+mc1.20.1 with version 0.5.1-d-build.1161+mc1.20.1.
More details:
	 - Mod 'Create Editions' (createeditions) 1.0.1+1.20.1_fabric requires version 0.5.1-d-build.1161+mc1.20.1 of mod 'Create' (create), but only the wrong version is present: 0.5.1-f-build.1417+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?]
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 19 May 2024 11:58:06 +0600
```

**Comment by jmcmahon1999** [comment]
I'm no longer updating this mod, because the functionality for it seems to now be included in Create. You may want to open an issue with them if the backtanks still don't support Trinket/Curios slots
